### ISSUE TITLE
Can it be added to the bottom Dock instead of the top panel?

### ISSUE THREAD

**Issue by probonopd** [SeptemberHX/dde-smart-dir#3]
Can it be added to the bottom Dock instead of the top panel?

If yes, how?

**Comment by SeptemberHX** [comment]
Yes, you can add it to dock.

Just copy the plugin *.so file to `/usr/lib/dde-dock/plugins` or `~/.local/lib/dde-dock/plugins`

**Comment by probonopd** [comment]
Thank you very much. This is very useful.
